const BOOKS = {
    mind: {
        title: "Philosophy of Mind: A Contemporary Introduction",
        author: "by John Heil (3rd Edition, 2013)",
        description: "Introduces central issues in philosophy of mind, focusing on the ontological basis of mentality and its place in the material world.",
        chapters: [
            {
                id: "ch1",
                title: "1. Introduction: Experience and Reality",
                summary: "Explores the gap between the physical world and conscious experience. Distinguishes primary qualities (intrinsic properties of objects) from secondary qualities (experiential properties like color, sound). Argues that philosophy of mind is unavoidable: any inquiry into mind eventually raises metaphysical questions about how mental phenomena fit into the material universe.",
                concepts: ["Primary Qualities", "Secondary Qualities", "Consciousness", "Mind-Body Problem"]
            },
            {
                id: "ch2",
                title: "2. Cartesian Dualism",
                summary: "Descartes divides reality into mental and material substances. Mental substances are nonspatial, qualitative, and known through privileged access. Material substances are spatial, public, and known through observation. The resulting mind-body problem: how can two radically different substances causally interact?",
                concepts: ["Cartesian Dualism", "Substance Dualism", "Mind-Body Problem", "Privileged Access", "Substances", "Attributes", "Modes"]
            },
            {
                id: "ch3",
                title: "3. Descartes's Legacy",
                summary: "Modifications of Cartesian dualism: Parallelism (Leibniz) avoids interaction by pre-established harmony; Occasionalism (Malebranche) uses God as intermediary; Epiphenomenalism allows one-way physical-to-mental causation; Idealism denies matter altogether.",
                concepts: ["Parallelism", "Occasionalism", "Epiphenomenalism", "Idealism"]
            },
            {
                id: "ch4",
                title: "4. Behaviorism",
                summary: "Behaviorists reject the Cartesian picture by analyzing mental states in terms of behavior or behavioral dispositions. Philosophical behaviorism (Ryle) holds that mental predicates can be analyzed into behavioral predicates. Psychological behaviorism (Skinner) treats psychology as the science of behavior, not internal states.",
                concepts: ["Behaviorism", "Dispositions", "Philosophical Behaviorism", "Psychological Behaviorism", "Other Minds"]
            },
            {
                id: "ch5",
                title: "5. The Identity Theory",
                summary: "Mental states are identical to brain states. Parsimony (Occam's Razor) motivates identifying the mental with the physical rather than postulating separate entities. Faces challenges from Leibniz's Law (if mental and physical properties differ, they can't be identical) and the Phenomenological Fallacy.",
                concepts: ["Identity Theory", "Mind-Brain Identity", "Parsimony", "Leibniz's Law", "Phenomenological Fallacy"]
            },
            {
                id: "ch6",
                title: "6. Functionalism",
                summary: "Mental states are defined by their functional roles (causal relations to inputs, outputs, and other states) rather than by their physical constitution. Mental states are multiply realizable: the same functional role can be played by different physical systems (human brain, octopus nervous system, silicon computer).",
                concepts: ["Functionalism", "Multiple Realizability", "Functional Roles", "Causal Roles"]
            },
            {
                id: "ch7",
                title: "7. The Representational Theory of Mind",
                summary: "Minds are information-processing devices that manipulate mental representations in a Language of Thought. Minds are like software running on neurological hardware. Searle's Chinese Room argument challenges whether syntax alone can produce semantics (meaning).",
                concepts: ["Representational Theory of Mind", "Language of Thought", "Mental Representations", "Chinese Room", "Syntax vs Semantics"]
            },
            {
                id: "ch8",
                title: "8. The Intentional Stance",
                summary: "Dennett proposes that having a mind is a matter of being usefully described from the intentional stance (attributing beliefs and desires). The design stance (how a system is built) and physical stance (physical laws) provide deeper explanations. Consciousness is treated as a kind of user-illusion.",
                concepts: ["Intentional Stance", "Design Stance", "Physical Stance", "Propositional Attitudes"]
            },
            {
                id: "ch9",
                title: "9. Eliminativism",
                summary: "Perhaps folk psychology (beliefs, desires) is a fundamentally flawed theory that will be eliminated by mature neuroscience, just as phlogiston theory was eliminated by chemistry. Stich argues that if cognitive science vindicates eliminativism, we should accept it. Critics worry eliminativism is self-refuting.",
                concepts: ["Eliminativism", "Folk Psychology", "Ontological Commitment", "Theory Reduction"]
            },
            {
                id: "ch10",
                title: "10. Consciousness",
                summary: "The 'hard problem' of consciousness: why and how do physical processes give rise to subjective experience (qualia)? Zombies (physically identical beings lacking consciousness) and Mary's Room (a colorblind scientist who learns something new upon seeing red) are key thought experiments. Options include representationalism, higher-order theories, and panpsychism.",
                concepts: ["Consciousness", "Qualia", "Hard Problem", "Zombies", "Mary's Room", "Panpsychism", "Representationalism", "Higher-Order Theory"]
            },
            {
                id: "ch11",
                title: "11. Non-Reductive Physicalism",
                summary: "Mental properties depend on physical properties (supervenience) but are not reducible to them. This faces the problem of mental causation: if mental properties are distinct from physical properties, how can they cause behavior? The exclusion argument suggests mental properties are causally irrelevant.",
                concepts: ["Non-Reductive Physicalism", "Supervenience", "Mental Causation", "Exclusion Problem", "Property Dualism"]
            },
            {
                id: "ch12",
                title: "12. Metaphysics and Mind",
                summary: "Heil's own ontological framework: substances possess properties, which are particularized ways of being (tropes). Properties are powerful qualities -- each property contributes both qualitative character and causal powers/dispositions to its possessor.",
                concepts: ["Substances", "Properties", "Tropes", "Powerful Qualities", "Dispositions", "Causality"]
            },
            {
                id: "ch13",
                title: "13. The Mind's Place in Nature",
                summary: "Heil applies his ontology to the mind: mental properties are higher-level properties of complex material systems, grounded in (but not identical to) lower-level physical properties. Addresses multiple realizability, levels of reality vs. levels of description, consciousness, intentionality, and concludes with a unified metaphysics of mind.",
                concepts: ["Levels of Reality", "Levels of Description", "Neutral Monism", "Intentionality", "Twin Earth"]
            }
        ],
        nodes: [
            { id: "Primary Qualities", group: 1, desc: "Intrinsic properties of objects (shape, mass, motion) that exist independently of observers." },
            { id: "Secondary Qualities", group: 1, desc: "Properties of objects that produce experiences in observers (color, sound, taste). Dependent on the observer." },
            { id: "Consciousness", group: 7, desc: "The subjective, experiential dimension of mental life. The 'hard problem' of philosophy of mind." },
            { id: "Mind-Body Problem", group: 1, desc: "The problem of explaining how mental phenomena relate to physical phenomena." },
            { id: "Cartesian Dualism", group: 2, desc: "Descartes's view that mind and body are two fundamentally different kinds of substance." },
            { id: "Substance Dualism", group: 2, desc: "The thesis that mental and physical are distinct substances with no overlapping properties." },
            { id: "Privileged Access", group: 2, desc: "The distinctive, direct way each person knows their own mental states, as opposed to others'." },
            { id: "Substances", group: 8, desc: "Individual, self-standing objects that possess properties. The basic building blocks of reality." },
            { id: "Attributes", group: 8, desc: "Essential properties that define what kind of substance something is (Descartes)." },
            { id: "Modes", group: 8, desc: "Particular ways a substance exhibits an attribute (e.g., a particular motion)." },
            { id: "Parallelism", group: 3, desc: "Leibniz's view that mind and body don't interact but run in parallel, pre-established harmony." },
            { id: "Occasionalism", group: 3, desc: "Malebranche's view that God mediates all mind-body interaction on each occasion." },
            { id: "Epiphenomenalism", group: 3, desc: "Mental events are causally inert byproducts of physical events. Physical-to-mental causation only." },
            { id: "Idealism", group: 3, desc: "The view that only minds and their contents exist. The material world is an idea in a mind." },
            { id: "Behaviorism", group: 4, desc: "The view that mental states should be analyzed in terms of behavior or behavioral dispositions." },
            { id: "Dispositions", group: 4, desc: "Tendencies or capacities to behave in certain ways under certain conditions." },
            { id: "Philosophical Behaviorism", group: 4, desc: "Mental predicates can be analyzed into behavioral predicates (Ryle)." },
            { id: "Psychological Behaviorism", group: 4, desc: "Psychology should study only observable behavior, not internal mental states (Skinner)." },
            { id: "Other Minds", group: 4, desc: "The problem of how we know that other people have minds, given that we can only observe their behavior." },
            { id: "Identity Theory", group: 5, desc: "Mental states are identical to brain states. Mind = Brain." },
            { id: "Mind-Brain Identity", group: 5, desc: "The specific claim that each type of mental state corresponds to a type of brain state." },
            { id: "Parsimony", group: 5, desc: "Occam's Razor: don't multiply entities beyond necessity. Favors identity over dualism." },
            { id: "Leibniz's Law", group: 5, desc: "If A and B are identical, they share all properties. If mental and physical differ, they can't be identical." },
            { id: "Phenomenological Fallacy", group: 5, desc: "The mistake of thinking that because experiences seem non-physical, they must be non-physical." },
            { id: "Functionalism", group: 6, desc: "Mental states are defined by their functional roles (causal relations to inputs, outputs, and other states), not physical constitution." },
            { id: "Multiple Realizability", group: 6, desc: "The same mental state can be realized by different physical systems (humans, aliens, machines)." },
            { id: "Functional Roles", group: 6, desc: "The pattern of causal relations that defines a mental state: what causes it, what it causes, what else it co-occurs with." },
            { id: "Causal Roles", group: 6, desc: "The causal contributions that mental states make within a system's overall economy." },
            { id: "Representational Theory of Mind", group: 6, desc: "Minds process mental representations. Thinking is manipulating symbols in a Language of Thought." },
            { id: "Language of Thought", group: 6, desc: "Hypothesized internal representational system with syntactic structure that underlies thinking." },
            { id: "Mental Representations", group: 6, desc: "Internal states that carry information about the world and mediate between input and output." },
            { id: "Chinese Room", group: 6, desc: "Searle's thought experiment: a person following rules to manipulate Chinese symbols doesn't understand Chinese, showing syntax isn't sufficient for semantics." },
            { id: "Syntax vs Semantics", group: 6, desc: "The distinction between formal symbol manipulation (syntax) and meaning (semantics)." },
            { id: "Intentional Stance", group: 7, desc: "Dennett's strategy of predicting behavior by attributing beliefs and desires. Having a mind = being predictably described this way." },
            { id: "Design Stance", group: 7, desc: "Explaining behavior by reference to how a system is designed to function." },
            { id: "Physical Stance", group: 7, desc: "Explaining behavior by reference to the physical laws governing a system's components." },
            { id: "Propositional Attitudes", group: 7, desc: "Mental states directed at propositions: believing that P, desiring that P, intending that P." },
            { id: "Eliminativism", group: 7, desc: "The radical view that folk psychology is fundamentally mistaken and will be replaced by mature neuroscience." },
            { id: "Folk Psychology", group: 7, desc: "The common-sense framework of beliefs, desires, and intentions used to explain and predict behavior." },
            { id: "Ontological Commitment", group: 7, desc: "What a theory says exists. If eliminativism is true, we have no ontological commitment to beliefs." },
            { id: "Theory Reduction", group: 7, desc: "Reducing one theory to another by showing the reduced theory's entities correspond to entities in the reducing theory." },
            { id: "Qualia", group: 7, desc: "The subjective, qualitative character of conscious experiences: the 'what it's like' aspect." },
            { id: "Hard Problem", group: 7, desc: "Chalmers's term for the problem of explaining why and how physical processes give rise to subjective experience." },
            { id: "Zombies", group: 7, desc: "Conceivable beings physically identical to us but lacking conscious experience. If possible, consciousness isn't physical." },
            { id: "Mary's Room", group: 7, desc: "Jackson's thought experiment: a colorblind scientist learns something new upon seeing red, suggesting physical knowledge doesn't exhaust all knowledge." },
            { id: "Panpsychism", group: 7, desc: "The view that consciousness or proto-consciousness is a fundamental feature of all matter." },
            { id: "Representationalism", group: 7, desc: "The view that the qualitative character of experience is determined by what the experience represents." },
            { id: "Higher-Order Theory", group: 7, desc: "Consciousness consists in having representations of one's own mental states (higher-order representations)." },
            { id: "Non-Reductive Physicalism", group: 9, desc: "Mental properties depend on physical properties but are not reducible to them. Substance monism + property dualism." },
            { id: "Supervenience", group: 9, desc: "Mental properties supervene on physical properties: no mental difference without a physical difference." },
            { id: "Mental Causation", group: 9, desc: "The problem of how mental states can cause physical behavior if they are not identical to physical states." },
            { id: "Exclusion Problem", group: 9, desc: "Kim's argument: if physical causes are sufficient, mental causes are excluded and become causally irrelevant." },
            { id: "Property Dualism", group: 9, desc: "The view that there are two fundamentally different kinds of property: physical and mental." },
            { id: "Properties", group: 8, desc: "Ways substances are. Particularized features that contribute to a substance's qualities and powers." },
            { id: "Tropes", group: 8, desc: "Particularized properties: this ball's redness, not redness-in-general. Each trope is unique." },
            { id: "Powerful Qualities", group: 8, desc: "Heil's view that every property is both qualitative (contributing to appearance) and dispositional (contributing to causal powers)." },
            { id: "Dispositions", group: 8, desc: "Powers or capacities to produce or undergo certain changes under appropriate conditions." },
            { id: "Causality", group: 8, desc: "The relation between cause and effect. How one event brings about another." },
            { id: "Levels of Reality", group: 9, desc: "The idea that reality has multiple levels: physical, chemical, biological, psychological, each with its own ontology." },
            { id: "Levels of Description", group: 9, desc: "The idea that there are multiple ways to describe the same reality, from physics to psychology." },
            { id: "Neutral Monism", group: 9, desc: "The view that the fundamental stuff of reality is neither mental nor physical, but neutral between them." },
            { id: "Intentionality", group: 9, desc: "The 'aboutness' of mental states: beliefs are about things, desires are for things." },
            { id: "Twin Earth", group: 9, desc: "Putnam's thought experiment: if 'water' on Twin Earth refers to XYZ rather than H2O, meaning ain't in the head." }
        ],
        links: [
            { source: "Primary Qualities", target: "Secondary Qualities", value: 2 },
            { source: "Primary Qualities", target: "Consciousness", value: 1 },
            { source: "Secondary Qualities", target: "Consciousness", value: 3 },
            { source: "Consciousness", target: "Mind-Body Problem", value: 3 },
            { source: "Cartesian Dualism", target: "Mind-Body Problem", value: 3 },
            { source: "Cartesian Dualism", target: "Substance Dualism", value: 3 },
            { source: "Cartesian Dualism", target: "Substances", value: 2 },
            { source: "Cartesian Dualism", target: "Attributes", value: 2 },
            { source: "Cartesian Dualism", target: "Modes", value: 2 },
            { source: "Cartesian Dualism", target: "Privileged Access", value: 2 },
            { source: "Cartesian Dualism", target: "Parallelism", value: 2 },
            { source: "Cartesian Dualism", target: "Occasionalism", value: 2 },
            { source: "Cartesian Dualism", target: "Epiphenomenalism", value: 2 },
            { source: "Cartesian Dualism", target: "Idealism", value: 2 },
            { source: "Mind-Body Problem", target: "Behaviorism", value: 2 },
            { source: "Mind-Body Problem", target: "Identity Theory", value: 2 },
            { source: "Mind-Body Problem", target: "Functionalism", value: 2 },
            { source: "Mind-Body Problem", target: "Eliminativism", value: 1 },
            { source: "Mind-Body Problem", target: "Consciousness", value: 3 },
            { source: "Mind-Body Problem", target: "Non-Reductive Physicalism", value: 2 },
            { source: "Behaviorism", target: "Philosophical Behaviorism", value: 3 },
            { source: "Behaviorism", target: "Psychological Behaviorism", value: 3 },
            { source: "Behaviorism", target: "Dispositions", value: 2 },
            { source: "Behaviorism", target: "Other Minds", value: 2 },
            { source: "Identity Theory", target: "Mind-Brain Identity", value: 3 },
            { source: "Identity Theory", target: "Parsimony", value: 2 },
            { source: "Identity Theory", target: "Leibniz's Law", value: 2 },
            { source: "Identity Theory", target: "Phenomenological Fallacy", value: 2 },
            { source: "Functionalism", target: "Multiple Realizability", value: 3 },
            { source: "Functionalism", target: "Functional Roles", value: 3 },
            { source: "Functionalism", target: "Causal Roles", value: 2 },
            { source: "Functionalism", target: "Representational Theory of Mind", value: 2 },
            { source: "Functionalism", target: "Behaviorism", value: 1 },
            { source: "Functionalism", target: "Identity Theory", value: 1 },
            { source: "Representational Theory of Mind", target: "Language of Thought", value: 3 },
            { source: "Representational Theory of Mind", target: "Mental Representations", value: 3 },
            { source: "Representational Theory of Mind", target: "Chinese Room", value: 2 },
            { source: "Chinese Room", target: "Syntax vs Semantics", value: 3 },
            { source: "Intentional Stance", target: "Design Stance", value: 3 },
            { source: "Intentional Stance", target: "Physical Stance", value: 3 },
            { source: "Intentional Stance", target: "Propositional Attitudes", value: 3 },
            { source: "Intentional Stance", target: "Eliminativism", value: 2 },
            { source: "Eliminativism", target: "Folk Psychology", value: 3 },
            { source: "Eliminativism", target: "Ontological Commitment", value: 2 },
            { source: "Eliminativism", target: "Theory Reduction", value: 2 },
            { source: "Consciousness", target: "Qualia", value: 3 },
            { source: "Consciousness", target: "Hard Problem", value: 3 },
            { source: "Consciousness", target: "Zombies", value: 2 },
            { source: "Consciousness", target: "Mary's Room", value: 2 },
            { source: "Consciousness", target: "Panpsychism", value: 2 },
            { source: "Consciousness", target: "Representationalism", value: 2 },
            { source: "Consciousness", target: "Higher-Order Theory", value: 2 },
            { source: "Consciousness", target: "Epiphenomenalism", value: 1 },
            { source: "Non-Reductive Physicalism", target: "Supervenience", value: 3 },
            { source: "Non-Reductive Physicalism", target: "Mental Causation", value: 3 },
            { source: "Non-Reductive Physicalism", target: "Exclusion Problem", value: 3 },
            { source: "Non-Reductive Physicalism", target: "Property Dualism", value: 3 },
            { source: "Mental Causation", target: "Exclusion Problem", value: 3 },
            { source: "Properties", target: "Tropes", value: 3 },
            { source: "Properties", target: "Powerful Qualities", value: 3 },
            { source: "Powerful Qualities", target: "Dispositions", value: 3 },
            { source: "Levels of Reality", target: "Levels of Description", value: 3 },
            { source: "Levels of Reality", target: "Multiple Realizability", value: 2 },
            { source: "Levels of Reality", target: "Neutral Monism", value: 1 },
            { source: "Intentionality", target: "Propositional Attitudes", value: 2 },
            { source: "Intentionality", target: "Twin Earth", value: 2 },
            { source: "Twin Earth", target: "Representational Theory of Mind", value: 1 },
            { source: "Substances", target: "Properties", value: 3 },
            { source: "Dispositions", target: "Causality", value: 2 },
            { source: "Qualia", target: "Hard Problem", value: 3 },
            { source: "Qualia", target: "Zombies", value: 2 },
            { source: "Panpsychism", target: "Consciousness", value: 2 }
        ]
    },

    metaphysics: {
        title: "Metaphysics: An Introduction",
        author: "by Alyssa Ney (2014)",
        description: "A comprehensive introduction to core elements of metaphysics with contemporary debates. Covers ontology, abstract objects, material objects, time, modality, causation, free will, and the metaphysics of race.",
        chapters: [
            {
                id: "mch0",
                title: "0. Logic for Metaphysics (Preparatory)",
                summary: "Tools for assessing arguments: validity (premises logically entail conclusion), soundness (valid + true premises). Propositional logic (connectives: and, or, not, if-then). First-order predicate logic (predicates, quantifiers: existential 'some' and universal 'all'). Principle of charity: interpret opponents' arguments as charitably as possible.",
                concepts: ["Arguments", "Validity", "Soundness", "Propositional Logic", "First-Order Logic", "Principle of Charity"]
            },
            {
                id: "mch1",
                title: "1. An Introduction to Ontology",
                summary: "Ontology is the study of what there is. Quine's method: existential commitment is determined by what must exist for our best total theory to be true. The method of paraphrase rewrites seemingly committed sentences to avoid ontological baggage. Ockham's Razor: don't multiply entities beyond necessity. Fundamental vs. non-fundamental metaphysics: ontological dependence.",
                concepts: ["Ontology", "Quine's Method", "Paraphrase", "Ockham's Razor", "Ontological Dependence"]
            },
            {
                id: "mch2",
                title: "2. Abstract Entities",
                summary: "Are there entities beyond the physical? The abstract/concrete distinction. Universals (properties shared by many) face the One Over Many argument. Nominalism denies universals exist. Mathematical objects (numbers, sets) raise Benacerraf's dilemma: are they abstract objects or useful fictions?",
                concepts: ["Abstract Entities", "Universals", "Nominalism", "One Over Many", "Mathematical Objects"]
            },
            {
                id: "mch3",
                title: "3. Material Objects",
                summary: "What counts as a material object? The Paradoxes of Material Constitution: the statue and the clay seem to be two objects in the same place. The Problem of the Many: how many objects compose something? The Special Composition Question: when do parts compose a whole? Mereological nihilism (no composites) vs. universalism (everything composes).",
                concepts: ["Material Objects", "Paradoxes of Constitution", "Problem of the Many", "Special Composition Question", "Mereological Nihilism", "Mereological Universalism"]
            },
            {
                id: "mch4",
                title: "4. Critiques of Metaphysics",
                summary: "Carnap argued metaphysical questions are meaningless pseudo-questions. Responses: metaphysics discovers real structure. Modern worries about metaphysical method: are we doing armchair science or something distinct? Proposal: metaphysics and science are continuous but metaphysics asks more general questions.",
                concepts: ["Carnap's Critique", "Pseudo-Questions", "Metaphysical Method"]
            },
            {
                id: "mch5",
                title: "5. Time",
                summary: "Time's passage seems real, but special relativity challenges this. The A-theory holds that temporal properties (past, present, future) are objective features of reality. The B-theory holds that only earlier-than/later-than relations are real. The Truthmaker Objection and time travel raise further puzzles.",
                concepts: ["A-Theory", "B-Theory", "Time's Passage", "Truthmaker Objection", "Time Travel", "Special Relativity"]
            },
            {
                id: "mch6",
                title: "6. Persistence",
                summary: "How do objects persist through change? Endurantism: objects are wholly present at each time they exist. Perdurantism (4Dism): objects have temporal parts at each time. Exdurantism (Stage Theory): objects are instantaneous stages. The Problem of Temporary Intrinsics: how can an object have different properties at different times?",
                concepts: ["Persistence", "Endurantism", "Perdurantism", "Exdurantism", "Temporary Intrinsics", "Ship of Theseus"]
            },
            {
                id: "mch7",
                title: "7. Modality",
                summary: "What is possibility and necessity? Possible Worlds Analysis: a proposition is possible iff true in some possible world, necessary iff true in all. But are possible worlds real (Lewis) or ersatz (abstract representations)? Essentialism: objects have some properties necessarily. The relation between essence and necessity.",
                concepts: ["Modality", "Possible Worlds", "Essentialism", "Ersatz Modal Realism", "Necessity"]
            },
            {
                id: "mch8",
                title: "8. Causation",
                summary: "What is causation? Hume's empiricism: causation is constant conjunction + temporal priority. Reductive theories: regularity, counterfactuals, probabilistic. Objection: these miss the 'causal connection'. Physical theories ground causation in physics. The problem of preemption: when does the actual cause differ from the enabling condition?",
                concepts: ["Causation", "Humean Regularity", "Counterfactuals", "Preemption", "Epiphenomena"]
            },
            {
                id: "mch9",
                title: "9. Free Will",
                summary: "If determinism is true (every event is caused by prior events + laws), is free will possible? Compatibilism: free will is compatible with determinism (freedom = acting on desires without external constraint). Libertarianism: free will requires indeterminism (agent causation). Hard determinism / Skepticism: free will is an illusion.",
                concepts: ["Free Will", "Determinism", "Compatibilism", "Libertarianism", "Skepticism about Free Will"]
            },
            {
                id: "mch10",
                title: "10. The Metaphysics of Race",
                summary: "Are races real? Natural kinds vs. social kinds. Three views: racial naturalism (races are biological), racial constructivism (races are socially constructed), eliminativism (races don't exist). Arguments from genetics, relativism, and anti-racism. A causal argument against eliminativism.",
                concepts: ["Metaphysics of Race", "Natural Kinds", "Social Kinds", "Racial Constructivism", "Eliminativism (Race)"]
            }
        ],
        nodes: [
            { id: "Arguments", group: 1, desc: "A series of statements presenting reasons in defense of a conclusion. Consists of premises and a conclusion." },
            { id: "Validity", group: 1, desc: "An argument is deductively valid when there is no possible way for its premises to all be true while its conclusion is false." },
            { id: "Soundness", group: 1, desc: "An argument is sound when it is valid and all its premises are actually true." },
            { id: "Propositional Logic", group: 1, desc: "A formal system using connectives (and, or, not, if-then) to represent and evaluate compound propositions." },
            { id: "First-Order Logic", group: 1, desc: "A formal system that adds predicates and quantifiers (existential, universal) to propositional logic, enabling reasoning about objects and their properties." },
            { id: "Principle of Charity", group: 1, desc: "A convention of philosophical debate: interpret opponents' claims as true and their arguments as valid when reasonably possible." },
            { id: "Ontology", group: 2, desc: "The study of what there is: the most general categories of entities that exist." },
            { id: "Quine's Method", group: 2, desc: "Determine ontological commitment by regimenting our best total theory in first-order logic; whatever must exist for the theory to be true is what we are committed to." },
            { id: "Paraphrase", group: 2, desc: "Rewriting sentences to avoid apparent ontological commitments (e.g., reifying nonexistent objects) without changing meaning." },
            { id: "Ockham's Razor", group: 2, desc: "The principle that entities should not be multiplied beyond necessity. Prefer simpler ontologies." },
            { id: "Ontological Dependence", group: 2, desc: "Entity A depends on entity B when A cannot exist without B. Grounding relation between levels of reality." },
            { id: "Abstract Entities", group: 3, desc: "Entities that lack spatiotemporal location: numbers, sets, properties, propositions. Contrast with concrete entities." },
            { id: "Universals", group: 3, desc: "Properties or relations that can be instantiated by multiple distinct particulars (e.g., redness, justice)." },
            { id: "Nominalism", group: 3, desc: "The view that only concrete, particular things exist. Universals are useful fictions or linguistic conventions." },
            { id: "One Over Many", group: 3, desc: "Argument for universals: many distinct things share a property; what explains the sharing? A universal they all instantiate." },
            { id: "Mathematical Objects", group: 3, desc: "Numbers, sets, functions. Are they abstract entities that exist independently, or useful fictions?" },
            { id: "Material Objects", group: 4, desc: "Physical entities that occupy space and persist through time. What are their criteria of identity?" },
            { id: "Paradoxes of Constitution", group: 4, desc: "Puzzles arising from multiple objects apparently occupying the same space at the same time (statue and clay)." },
            { id: "Problem of the Many", group: 4, desc: "How many objects are there when we consider all slightly different arrangements of parts?" },
            { id: "Special Composition Question", group: 4, desc: "Under what conditions do parts compose a whole object? Always? Sometimes? Never?" },
            { id: "Mereological Nihilism", group: 4, desc: "The view that no composite objects exist: only simple, partless entities exist." },
            { id: "Mereological Universalism", group: 4, desc: "The view that any collection of objects composes a further object." },
            { id: "Carnap's Critique", group: 5, desc: "Carnap's argument that metaphysical questions are meaningless pseudo-questions that can be dissolved by linguistic analysis." },
            { id: "Pseudo-Questions", group: 5, desc: "Questions that appear meaningful but are actually senseless, arising from misuse of language." },
            { id: "Metaphysical Method", group: 5, desc: "How should we do metaphysics? A priori reasoning, empirical input, or a combination?" },
            { id: "A-Theory", group: 6, desc: "The view that past, present, and future are genuine objective features of reality. Time genuinely passes." },
            { id: "B-Theory", group: 6, desc: "The view that only earlier-than and later-than relations are real. The present is not privileged. Time doesn't 'flow'." },
            { id: "Time's Passage", group: 6, desc: "The apparent fact that time flows or passes. Is this an objective feature of reality or a subjective illusion?" },
            { id: "Truthmaker Objection", group: 6, desc: "Objection to B-theory: what makes propositions about the past/future true if past/future objects don't exist?" },
            { id: "Time Travel", group: 6, desc: "The possibility of traveling to other times. Raises paradoxes about causation and persistence." },
            { id: "Special Relativity", group: 6, desc: "Einstein's theory implying that simultaneity is relative, challenging absolute presentness." },
            { id: "Persistence", group: 7, desc: "How objects continue to exist through change and over time." },
            { id: "Endurantism", group: 7, desc: "Objects are three-dimensional and wholly present at each time they exist. They endure through time." },
            { id: "Perdurantism", group: 7, desc: "Objects are four-dimensional and have temporal parts (time-slices) at each time they exist. They perdure." },
            { id: "Exdurantism", group: 7, desc: "Stage Theory: objects are instantaneous stages related by causal/temporal continuity, not persisting substances." },
            { id: "Temporary Intrinsics", group: 7, desc: "Properties an object has at one time but not another (being sitting, being warm). How can one object have contradictory properties?" },
            { id: "Modality", group: 8, desc: "The study of possibility and necessity. What could have been different? What must be the case?" },
            { id: "Possible Worlds", group: 8, desc: "Complete ways the world could have been. Lewis: they are concrete real entities. Others: they are abstract representations." },
            { id: "Essentialism", group: 8, desc: "Objects have some properties necessarily: they couldn't exist without them (e.g., a human's humanness)." },
            { id: "Ersatz Modal Realism", group: 8, desc: "Possible worlds are not concrete realities but abstract representations (sets of propositions, maximal consistent states)." },
            { id: "Necessity", group: 8, desc: "A proposition is necessary if it is true in every possible world." },
            { id: "Causation", group: 9, desc: "The relation between cause and effect. What does it mean for one event to bring about another?" },
            { id: "Humean Regularity", group: 9, desc: "Hume's view: causation is just constant conjunction (events of type A always followed by events of type B) plus temporal priority." },
            { id: "Counterfactuals", group: 9, desc: "C is caused by E iff: if C hadn't occurred, E wouldn't have occurred. Causal claims analyzed via counterfactual dependence." },
            { id: "Preemption", group: 9, desc: "Cases where the actual cause preempts a backup cause. Challenges counterfactual and regularity analyses." },
            { id: "Free Will", group: 10, desc: "The capacity to act freely: to have done otherwise under the same circumstances." },
            { id: "Determinism", group: 10, desc: "The thesis that every event is causally necessitated by prior events plus the laws of nature." },
            { id: "Compatibilism", group: 10, desc: "Free will is compatible with determinism. Freedom consists in acting according to one's own desires without external constraint." },
            { id: "Libertarianism", group: 10, desc: "Free will requires indeterminism. The agent is the ultimate originator of their actions (agent causation)." },
            { id: "Metaphysics of Race", group: 11, desc: "Are races real? Social construction? Natural kinds? Eliminable categories?" },
            { id: "Natural Kinds", group: 11, desc: "Categories that carve nature at its joints: biological species, chemical elements. Does race qualify?" },
            { id: "Social Kinds", group: 11, desc: "Categories constituted by social practices, beliefs, and institutions rather than intrinsic natural features." },
            { id: "Racial Constructivism", group: 11, desc: "Races are real but socially constructed: they exist because of social practices and conventions." },
            { id: "Eliminativism (Race)", group: 11, desc: "The view that races do not exist as real categories; racial talk should be eliminated." }
        ],
        links: [
            { source: "Arguments", target: "Validity", value: 3 },
            { source: "Validity", target: "Soundness", value: 3 },
            { source: "Arguments", target: "Propositional Logic", value: 2 },
            { source: "Propositional Logic", target: "First-Order Logic", value: 3 },
            { source: "Arguments", target: "Principle of Charity", value: 2 },
            { source: "Ontology", target: "Quine's Method", value: 3 },
            { source: "Ontology", target: "Paraphrase", value: 2 },
            { source: "Ontology", target: "Ockham's Razor", value: 3 },
            { source: "Ontology", target: "Ontological Dependence", value: 2 },
            { source: "Abstract Entities", target: "Universals", value: 3 },
            { source: "Abstract Entities", target: "Nominalism", value: 3 },
            { source: "Universals", target: "One Over Many", value: 3 },
            { source: "Abstract Entities", target: "Mathematical Objects", value: 3 },
            { source: "Mathematical Objects", target: "Nominalism", value: 2 },
            { source: "Material Objects", target: "Paradoxes of Constitution", value: 3 },
            { source: "Material Objects", target: "Problem of the Many", value: 2 },
            { source: "Material Objects", target: "Special Composition Question", value: 3 },
            { source: "Special Composition Question", target: "Mereological Nihilism", value: 3 },
            { source: "Special Composition Question", target: "Mereological Universalism", value: 3 },
            { source: "Ontology", target: "Material Objects", value: 2 },
            { source: "Ontology", target: "Abstract Entities", value: 2 },
            { source: "Carnap's Critique", target: "Pseudo-Questions", value: 3 },
            { source: "Carnap's Critique", target: "Metaphysical Method", value: 3 },
            { source: "A-Theory", target: "B-Theory", value: 3 },
            { source: "A-Theory", target: "Time's Passage", value: 3 },
            { source: "B-Theory", target: "Truthmaker Objection", value: 2 },
            { source: "B-Theory", target: "Special Relativity", value: 2 },
            { source: "Time Travel", target: "A-Theory", value: 1 },
            { source: "Time Travel", target: "B-Theory", value: 1 },
            { source: "Persistence", target: "Endurantism", value: 3 },
            { source: "Persistence", target: "Perdurantism", value: 3 },
            { source: "Persistence", target: "Exdurantism", value: 3 },
            { source: "Persistence", target: "Temporary Intrinsics", value: 2 },
            { source: "Perdurantism", target: "Exdurantism", value: 2 },
            { source: "Modality", target: "Possible Worlds", value: 3 },
            { source: "Modality", target: "Essentialism", value: 3 },
            { source: "Modality", target: "Necessity", value: 3 },
            { source: "Possible Worlds", target: "Ersatz Modal Realism", value: 3 },
            { source: "Possible Worlds", target: "Essentialism", value: 2 },
            { source: "Causation", target: "Humean Regularity", value: 3 },
            { source: "Causation", target: "Counterfactuals", value: 3 },
            { source: "Causation", target: "Preemption", value: 2 },
            { source: "Humean Regularity", target: "Counterfactuals", value: 2 },
            { source: "Free Will", target: "Determinism", value: 3 },
            { source: "Free Will", target: "Compatibilism", value: 3 },
            { source: "Free Will", target: "Libertarianism", value: 3 },
            { source: "Determinism", target: "Compatibilism", value: 3 },
            { source: "Determinism", target: "Libertarianism", value: 3 },
            { source: "Metaphysics of Race", target: "Natural Kinds", value: 2 },
            { source: "Metaphysics of Race", target: "Social Kinds", value: 3 },
            { source: "Metaphysics of Race", target: "Racial Constructivism", value: 3 },
            { source: "Metaphysics of Race", target: "Eliminativism (Race)", value: 3 },
            { source: "Natural Kinds", target: "Social Kinds", value: 2 },
            { source: "Ontological Dependence", target: "Ontology", value: 2 },
            { source: "Causation", target: "Free Will", value: 2 },
            { source: "Modality", target: "Free Will", value: 2 },
            { source: "Material Objects", target: "Persistence", value: 2 },
            { source: "Quine's Method", target: "Abstract Entities", value: 2 },
            { source: "First-Order Logic", target: "Quine's Method", value: 2 },
            { source: "A-Theory", target: "Time Travel", value: 1 },
            { source: "B-Theory", target: "Time Travel", value: 1 }
        ]
    }
};
